# -*- coding: utf-8 -*-
"""Copy of PCA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b_ODbiKnBgchOCCNbw2fHIX0Zi79pgME
"""

# Commented out IPython magic to ensure Python compatibility.
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
# %matplotlib inline

from sklearn.datasets import load_diabetes

dia=load_diabetes()

dia.keys()

X, Y = dia.data, dia.target

print(dia['DESCR'])

df=pd.DataFrame(dia['data'],columns=dia['feature_names'])

df.head(5)

from sklearn.decomposition import PCA

pca=PCA(n_components=2)

pca.fit(df)

x_pca=pca.transform(df)

df.shape

x_pca.shape

df

x_pca

plt.figure(figsize=(8,6))
plt.scatter(x_pca[:,0],x_pca[:,1],c=dia['target'])
plt.xlabel('First principle component')
plt.ylabel('Second principle component')

from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=4)

pip install --upgrade scikit-learn==0.20.3

from mlxtend.feature_selection import SequentialFeatureSelector as SFS

sfs1 = SFS(knn,
           k_features=3,
           forward=True,
           floating=False,
           verbose=2,
           scoring='accuracy',
           cv=0)

sfs1 = sfs1.fit(X, Y)

sfs1.subsets_

feature_names = ('age', 'sex', 'bmi', 'bp','s1','s2','s3','s4','s5','s6')
sfs1 = sfs1.fit(X, Y, custom_feature_names=feature_names)
sfs1.subsets_

sfs1.k_feature_idx_

sfs1.k_feature_names_

sfs1.k_score_